require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  Exclude:
    - "bin/**/*"
    - "overt.gemspec"
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    
Metrics/MethodLength:
  Max: 15

Style/StringLiterals:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

Style/Documentation:
  Enabled: false
